Repository muexxl/batcontrol, pull requests merged in 2025-02, with the labels that each got.

#116 Add options to tweak batcontrol behavior
  batcontrol.py
  config/batcontrol_config_dummy.yaml
Labels: enhancement, ConfigChange

#117 Dynamic price limit
  batcontrol.py
  config/batcontrol_config_dummy.yaml
  mqtt_api.py
Labels: enhancement, ConfigChange

#121 implements HA mqtt autodiscovery config messages
  config/batcontrol_config_dummy.yaml
  mqtt_api.py
Labels: enhancement, ConfigChange

#122 Fronius rework send_request and login handling
  inverter/fronius.py
Labels: bug

#123 Pylint improvements 5
  batcontrol.py
  logfilelimiter/logfilelimiter.py
Labels: CodeQuality

#127 mqtt_api: more graceful handling with auto_discovery config
  mqtt_api.py
Labels: enhancement

#126 Enhance Fronius inverter authentication handling and logging
  inverter/fronius.py
Labels: bug

#131 Fronius : Expose Ei­gen­ver­brauchs-Op­ti­mie­rung" to MQTT Endpoint and Code
  inverter/fronius.py
Labels: enhancement
