Repository muexxl/batcontrol, pull requests merged in 2025-03, with the labels that each got.

#141 Improve Project structure with python packaging standards
  .github/workflows/pylint.yml
  .gitignore
  Dockerfile
  README.MD
  __init__.py
  dynamictariff/__init__.py
  entrypoint.sh
  entrypoint_ha.sh
  forecastconsumption/__init__.py
  forecastsolar/__init__.py
  inverter/__init__.py
  logfilelimiter/__init__.py
  pyproject.toml
  requirements.txt
  src/batcontrol/__init__.py
  src/batcontrol/__main__.py
  src/batcontrol/__pkginfo__.py
  src/batcontrol/core.py
  src/batcontrol/dynamictariff/__init__.py
  src/batcontrol/dynamictariff/awattar.py
  src/batcontrol/dynamictariff/baseclass.py
  src/batcontrol/dynamictariff/dynamictariff.py
  src/batcontrol/dynamictariff/dynamictariff_interface.py
  src/batcontrol/dynamictariff/evcc.py
  src/batcontrol/dynamictariff/tibber.py
  src/batcontrol/evcc_api.py
  src/batcontrol/forecastconsumption/__init__.py
  src/batcontrol/forecastconsumption/consumption.py
  src/batcontrol/forecastconsumption/forecast_csv.py
  src/batcontrol/forecastconsumption/forecastconsumption_interface.py
  src/batcontrol/forecastsolar/__init__.py
  src/batcontrol/forecastsolar/fcsolar.py
  src/batcontrol/forecastsolar/forecastsolar_interface.py
  src/batcontrol/forecastsolar/solar.py
  src/batcontrol/inverter/__init__.py
  src/batcontrol/inverter/baseclass.py
  src/batcontrol/inverter/fronius.py
  src/batcontrol/inverter/inverter.py
  src/batcontrol/inverter/inverter_interface.py
  src/batcontrol/inverter/testdriver.py
  src/batcontrol/logfilelimiter/__init__.py
  src/batcontrol/logfilelimiter/logfilelimiter.py
  src/batcontrol/mqtt_api.py
Labels: CodeQuality, DependencyChange

#138 Add solarprognose.de to possible providers
  config/batcontrol_config_dummy.yaml
  src/batcontrol/forecastsolar/solar.py
  src/batcontrol/forecastsolar/solarprognose.py
Labels: enhancement, ConfigChange

#145 Code Cleanups
  src/batcontrol/__main__.py
  src/batcontrol/core.py
  src/batcontrol/dynamictariff/dynamictariff.py
Labels: CodeQuality

#148 Fix docker build pipeline
  Dockerfile
Labels: bug

#152 Fronius: next 01:00 o'clock fix
  src/batcontrol/inverter/fronius.py
Labels: bug
