Repository muexxl/batcontrol, pull requests merged in 2025-01, with the labels that each got.

#102 Refactor pylint workflow to analyze only changed Python files
  .github/workflows/pylint.yml
Labels: CodeQuality

#103 introduce proper OS-level timezone handling in Docker setup
  Dockerfile
  README.MD
  entrypoint.sh
Labels: bug, enhancement

#110 Add query parameter to allow modification of horizon used to forecast PV production in fcsolar.py
  config/batcontrol_config_dummy.yaml
  forecastsolar/fcsolar.py
Labels: enhancement
